### PR TITLE
Example tunning

### PR DESCRIPTION
**Pull request by vencax**
Hi, I have spent some time with blog example, clean up a bit, ant split into modules. Maybe you can find that useful. Bye

### CODE REVIEW

**Comment by fzaninotto** [comment]
Great! But to split an admin config into modules, the best idea is to create all entities first, so that references are made easier. See for instance [how it was done in ng-admin-demo](https://github.com/marmelab/ng-admin-demo/blob/9b9c9e15311cd72edddde7c2b54081791f7ab7d4/js/main.js#L37-L51).

**Comment by vencax** [comment]
Yeah, it is in fact done this way in my code. With one little difference, that I send to module init function even one more param - name of da entity. If I think about this param now, I realize that it is unnecessary.
Or am I missing somth. else?

**Comment by fzaninotto** [comment]
I never needed this name param in my implementations.

**Comment by vencax** [comment]
Yeah, I revrote the example. Now it is ok?

**Comment by fzaninotto** [comment]
Thanks!

**Comment by fzaninotto** [comment]
I had to revert your PR because it broke tests. Please open a new one and check CI result.

**Pull request merged**
